### PR TITLE
GH-80 UseCases: Fix CancellationException handling and add tests

### LINKED ISSUE #80: CancellationExceptions are propagated to onError handler
When executing UseCase from `UseCaseExecutionScope`, the `CancellationException`s are propagated to `onError` handler. If you're showing error dialogs after unsuccessful operations, this might display such dialog before navigating away from screen, when viewModel scope is canceled.

This did not happen in original Arkitekt's [CoroutineScopeOwner](https://github.com/futuredapp/arkitekt/blob/5.x/cr-usecases/src/main/java/app/futured/arkitekt/crusecases/CoroutineScopeOwner.kt)

### PR DESCRIPTION
**Pull request by matejsemancik**
Resolves #80

### CODE REVIEW

File: shared/util/src/commonMain/kotlin/app/futured/kmptemplate/util/domain/scope/SingleUseCaseExecutionScope.kt [hunk 1]
```diff
@@ -47,13 +46,20 @@ interface SingleUseCaseExecutionScope : CoroutineScopeOwner {
...
-                    kotlin.runCatching { it.await() }
-                        .fold(useCaseConfig.onSuccess, useCaseConfig.onError)
+                viewModelScope.launch(Dispatchers.Main) {
+                    try {
+                        useCaseConfig.onSuccess(it.await())
+                    } catch (cancellation: CancellationException) {
+                        // do nothing - this is normal way of suspend function interruption
+                    } catch (error: Throwable) {
+                        UseCaseErrorHandler.globalOnErrorLogger(error)
+                        useCaseConfig.onError.invoke(error)
```
Comment (Syntey) [inline shared/util/src/commonMain/kotlin/app/futured/kmptemplate/util/domain/scope/SingleUseCaseExecutionScope.kt:61]:
```suggestion
                        useCaseConfig.onError(error)
```

**Review by Syntey — DISMISSED** [review]

**Review by Syntey — APPROVED** [review]
